# Generated by Django 5.0 on 2023-12-27 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_person', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=100)),
                ('umur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jamil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pekerjaan', models.CharField(max_length=100)),
                ('status', models.TextField()),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.person')),
            ],
        ),
    ]
