# Generated by Django 5.0 on 2023-12-27 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Induk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_induk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Anak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('umur', models.IntegerField()),
                ('Induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.induk')),
            ],
        ),
    ]
